INSERT INTO candy
    (candy_type, candy_name, picture, candy_description, price)
    VALUES 
    ('gummies', 'Haribo Goldbears', 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRYC_QUBXYEzUp-k1LmuCFD7ZgKn2v_9tybWQ-DThCQ3yQqX7_4NnQsPpzZtd4MaSKFn011P-B-S11KTTmLr3Gl8BshGlRUsGRpCfy4W1GK33xL0Ucjiivz&usqp=CAE', 'If you know gummi bears then you have heard of Haribo. Haribo was the first manufacturer to make gummi bears and they have been doing it for over 90 years. There Gold Bears are the finest of them all. The unique flavors and quality are unequaled to any in the gummi bear game.This 5 pound bulk bag will give you all the traditional flavors that have the Haribo Gold Bears so famous. So order your today and enjoy a piece of candy history.', 12.99), ('gummies', 'Black Forest', 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRVes2xDPnt6E9POug6B6HXJUATz-VNeSiQUExBn-jQ8Dot_4vNvfOZaiILH8jtXAAmj86nDLx0brVE_JQMOXHlFr9pFEgiHbVAVC9tavRkbS4MFCmK-ZQtkw&usqp=CAE', 'From the Makers of America’s Best Tasting Gummy Bear, Black Forest Fruit Medley Flavored Snacks contain juicy centers. Who can pick between the grape, apple, lemon and cherry flavored gummies? They’re all delicious. And they’re in every pouch of Black Forest Fruit Medleys Fruit Snacks. These juicy filled snacks provide 100 percent daily value of Vitamin C. As every pouch is packed with real fruit juice, the Fruit Medley gummies deliver big time deliciousness. Black Forest thinks you deserve the best of everything.', 15.99), 
    ('chocolate', 'Twix', 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcREVxAZaGZCkUSquYUdtzG1Kepsu0ZyCiq9a3-_Htkj6uQ17Q2fhNqJR_IRawVQ-i2NoUgeUIaZRD6F6tMZOwvemQB3MTGDipcjZ1gDPpmgn-KJwBFuKXbL&usqp=CAE', 'Crispy cookie topped with caramel and covered with milk chocolate Gooey caramel and delicious chocolate with just the right bit of crunch Use the treat as party favours, for baking or a treat on the go Twix is best enjoyed when shared; choose your side Twix Left or Twix Right. Delectable cookie and luscious caramel on both sides, it wont be an easy choice.', 3.99),
    ('chocolate', 'Kit Kat', 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSAxRJoiIVim9MQ1Dy1l2csplGeFPW1rIa076LqugMTUfjK7i1p3KNV7RqFQhVkCppU7zUoKXqywMTbR08g255101uhRoKvIDr6rdcavOoCHsJpuFtks_lyRw&usqp=CAE', "Kit Kat Bars are the perfect size for any snack occasion or holiday celebration. An all time favorite Hershey's treat are great for your pantry - enjoy as everyday snacks and lunch box treats.", 4.99),
    ('hard candy', 'Jolly Rancher', 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQE0R-VVRxgLRjeTxyq9qxUiUnW8fuCGQQt9nRbVTUGftTsGq2RMjG5MuGT4zIQb6sQnJ8nQMHDPkSxenI1FtecixH4sBIPpJ-eKRnTFG7K2DK3hAcPn-1X&usqp=CAE', "Jolly Rancher Hard Candies offer a long-lasting burst of fruit flavor that's the perfect anytime treat.", 14.99),
    ('hard candy', 'Life Savers', 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcT6tpJPeqCkHeNgWBGgNrXNtfFd1JkmycUVJiB8kbkM6eIpP7NcXjgA-JbFmQGeFinI28ei_stjgju2wRC-TJmerCncX6t2GQ&usqp=CAE', 'A classic American candy since 1912, the flavors of Life Savers Hard Candy have stood the test of time.', 5.99),
    ('cake pop', 'Red Velvet', 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSgHJB80Wvkld6xY2H1v77-0rUOzp96wIP39F44O68vbOF76buTWdeKRvOaKOESrhBkvtX0sBqsIxxiZEndV-bIMayzTOmpzGIa5fkDA-uRqGkQL5mDNrEH&usqp=CAE', 'Red Velvet Cake pops * 1 Dozen Moist Red Velvet cake, mixed with sweet cream cheese frosting, dipped in white chocolate and drizzled in white chocolate flavored red chocolate.', 20.99),
    ('cake pop', 'Carrot Cake', 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTOhwq-lAsRVjOlBTP8V5npQIx19GUBTMPBdZTKjH34PyQw4HBEDZPdEw_QplTmJMLF_YbIbNbsSzpHB7FpmNATT0xINS3oOVzEEGvlcAsxQBXQASy2FYJl&usqp=CAE', 'If you love carrot cake as much as we do you will love these bite sized treats! Packed with real carrots and raisins this is one of our best sellers enjoyed in cake size and small cake pop sizes like this one. This listing is for one order of 12 cake pops.', 35.99);